### ISSUE TITLE
ggradar package is needed for "visualize"

### ISSUE THREAD

**Issue by BrandNewJimZhang** [sammo3182/drhur#15]
For further reference, if users do `drhur("visualize")` and terminal echos

```
package 'ggradar' is not available for this version of R
```

`ggradar` is not a package published on CRAN, it can be installed via `devtools`:

```
install.packages("devtools")
devtools::install_github("ricardo-bion/ggradar", dependencies=TRUE)
```

**Comment by sammo3182** [comment]
Thank you, @BrandNewJimZhang! The error should be fixed in the latest developed version and there will be a new released version coming soon.
