### ISSUE TITLE
parameters available for drhur()

### ISSUE THREAD

**Issue by Theta-u** [sammo3182/drhur#16]
Where can I see the input parameters available for drhur please? For example 'efa', which is not written in the documentation.

**Comment by sammo3182** [comment]
Hi @Theta-u , all the available modules have been documented in the help file (`help(drhur)`) which does not include the efa training. We do have a module to show how to do basic latent variable analysis in R, but it is only available for registered students of "Learning R with Dr. Hu." Please learn more info about the workshop on [my web site](https://sammo3182.github.io/course/method-series/03-r-workshop/). Let me know if you have further questions.
